import type { Metadata } from "next";
import { Box, ColorModeScript, UIProvider } from "@yamada-ui/react"
import { Header, Footer } from "./_components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <ColorModeScript />
        <UIProvider>
          <Header />
          <Box mt="xl">
            {children}
          </Box>
          <Footer />
        </UIProvider>
      </body>
    </html>
  );
}
